version: "3.7"

volumes:
  nhm:
    driver: local

networks:
  nhmnet:

services:
  anon_ftp:
    image: metabrainz/docker-anon-ftp
    container_name: ftp
    hostname: nhmusgsftp
    networks:
      nhmnet:
        aliases:
          - nhmusgsftp
    environment:
      - ANON_MAX_RATE=0

  data_loader:
    environment:
      - HRU_SOURCE=ftp://nhmusgsftp/Data_hru_shp_v2.tar.gz
      - PRMS_SOURCE=ftp://nhmusgsftp/NHM-PRMS_CONUS.zip
    depends_on:
      - anon_ftp

volumes:
  data:
