version: "3.2"
services:
  ofp:
    build: .
    image: nhmusgs/ofp
    hostname: ofp
    container_name: ofp
    environment:
      - DAYS=60
    volumes:
      - nhm:/var/lib/nhm
    entrypoint: /usr/local/bin/nhm
  prms:
    build: .
    image: nhmusgs/prms
    hostname: prms
    container_name: prms
volumes:
  nhm:
    driver: local
